arrays
1 delete 
2 insert
3 revese
4 
public
private
--------------------------------------------------
constructor
(method over loading)
1)same name as class
2)it doesn't have return type
it called it self
3)only called ones (automatically),at begin creation
4)memory allocation happens when cos is called

three types constructor
1)non perametised
2)perameterised
3)copy constructor
------------------------
copy constructor:













